export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR';
export const LOADING_REQUEST_START = 'LOADING_REQUEST_START';
export const LOADING_REQUEST_END = 'LOADING_REQUEST_END';