export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR';

export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';

export const LOADING_REQUEST_END = 'LOADING_REQUEST_END';

export const LOADING_REQUEST_START = 'LOADING_REQUEST_START';

export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SET_PROJECT_TO_CREATE_DATA = 'SET_PROJECT_TO_CREATE_DATA';

export const SET_PROJECT_TO_DISPLAY = 'SET_PROJECT_TO_DISPLAY';

export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
